apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: registry-ui-ingress
  namespace: registry-ui
spec:
  ingressClassName: nginx
  rules:
    - host: registry-ui.bastian-somon.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry-ui
                port:
                  number: 80
